import { Router, Request, Response, NextFunction } from 'express';
import jwt from 'jsonwebtoken';
import crypto from 'crypto';
import rateLimit from 'express-rate-limit';
import { JWT_SECRET } from '../config/env';
import { User } from '../models/user.model';
import { CommunityQuestion } from '../models/CommunityQuestion';
import { CommunityNotification } from '../models/CommunityNotification';

const router = Router();
export const COMMUNITY_CATEGORIES = ['AI Tools','Prompt Engineering','Writing','Coding','Marketing','Business','Design','Productivity','QuickTools Help'];
const writeLimiter = rateLimit({ windowMs: 15 * 60 * 1000, max: 20, standardHeaders: true, legacyHeaders: false });
const clean = (value: unknown, max: number) => String(value || '').replace(/<script[\s\S]*?<\/script>/gi, '').replace(/<[^>]+>/g, '').trim().slice(0, max);
const slugify = (value: string) => value.toLowerCase().replace(/[^a-z0-9\s-]/g, '').trim().replace(/\s+/g, '-').replace(/-+/g, '-');
const hash = (value: string) => crypto.createHash('sha256').update(value).digest('hex');
const actorKey = (actor: any) => actor.userId ? `u:${actor.userId}` : `g:${actor.guestId}`;

async function optionalUser(req: any, _res: Response, next: NextFunction) {
  try { const token = req.headers.authorization?.split(' ')[1] || req.cookies?.token; if (token) { const decoded: any = jwt.verify(token, JWT_SECRET); req.communityUser = await User.findById(decoded.id || decoded.userId).select('name avatar email'); } } catch { /* guest */ }
  next();
}
const actor = (req: any) => req.communityUser ? { userId: req.communityUser._id } : { guestId: clean(req.body?.guestId || req.headers['x-guest-id'], 80) || `ip-${hash(req.ip).slice(0,16)}` };
const owns = (doc: any, req: any, secret?: string) => req.communityUser ? String(doc.author?.userId || '') === String(req.communityUser._id) : Boolean(secret && doc.guestSecretHash && hash(secret) === doc.guestSecretHash);
const trendScore = (q: any) => q.views + q.likedBy.length * 3 + q.answers.filter((x:any)=>x.status==='visible').length * 5;
const serialize = (q: any, req: any, detail = false, isTrending = false) => { const a = actor(req); const key = actorKey(a); const base: any = { id:q._id,slug:q.slug,title:q.title,excerpt:q.excerpt,category:q.category,tags:q.tags,author:q.author,likes:q.likedBy.length,answersCount:q.answers.filter((x:any)=>x.status==='visible').length,views:q.views,createdAt:q.createdAt,updatedAt:q.updatedAt,isLiked:q.likedBy.some((x:any)=>actorKey(x)===key),isSaved:q.savedBy.some((x:any)=>actorKey(x)===key),isOwner:req.communityUser ? String(q.author?.userId||'')===String(req.communityUser._id) : false,trendingScore:trendScore(q),isTrending }; if(detail){base.body=q.body;} let visibleAnswers = q.answers.filter((x:any)=>x.status==='visible').sort((x:any,y:any)=>Number(y.isAccepted)-Number(x.isAccepted)||new Date(y.createdAt).getTime()-new Date(x.createdAt).getTime()); if(!detail) visibleAnswers = visibleAnswers.slice(0,2); base.answers = visibleAnswers.map((x:any)=>{ const replies=(x.replies||[]).filter((r:any)=>r.status==='visible'); return {...x.toObject?.()||x,likes:x.likedBy.length,isLiked:x.likedBy.some((v:any)=>actorKey(v)===key),likedBy:undefined,isOwner:req.communityUser?String(x.author?.userId||'')===String(req.communityUser._id):false,repliesCount:replies.length,replies:replies.slice(0, detail ? undefined : 2).map((r:any)=>({...r.toObject?.()||r,likes:r.likedBy?.length||0,isLiked:r.likedBy?.some((v:any)=>actorKey(v)===key),likedBy:undefined,isOwner:req.communityUser?String(r.author?.userId||'')===String(req.communityUser._id):false}))};}); return base; };

async function awardXP(userId: any, xpAmount: number) {
  if (!userId) return;
  const user = await User.findById(userId);
  if (!user) return;
  user.xp = (user.xp || 0) + xpAmount;
  
  // Calculate level (1000 XP per level, min level 1)
  const calculatedLevel = Math.max(1, Math.floor(user.xp / 1000));
  if (calculatedLevel > (user.level || 1)) {
    user.level = calculatedLevel;
  }
  
  // Auto-award basic badges
  if (user.level >= 10 && !user.badges.includes('AI Expert')) user.badges.push('AI Expert');
  
  await user.save();
}

router.use(optionalUser);
router.get('/meta', async (_req,res)=>{ const grouped=await CommunityQuestion.aggregate([{ $match:{status:'visible'} },{$group:{_id:'$category',count:{$sum:1}}},{$sort:{count:-1}}]); const contributors=await CommunityQuestion.aggregate([{$match:{status:'visible'}},{$group:{_id:'$author.name',avatar:{$first:'$author.avatar'},count:{$sum:{$add:[1,{$size:{$ifNull:['$answers',[]]}}]}}}},{$sort:{count:-1}},{$limit:5}]); res.json({success:true,data:{categories:COMMUNITY_CATEGORIES.map(name=>({name,count:grouped.find(x=>x._id===name)?.count||0})),contributors}}); });
router.get('/suggestions', async (req,res)=>{ const q=clean(req.query.q,100); if(q.length<3)return res.json({success:true,data:[]}); const rows=await CommunityQuestion.find({status:'visible',$text:{$search:q}}).select('title slug category').limit(5).lean(); res.json({success:true,data:rows}); });
router.get('/questions', async (req:any,res)=>{ const page=Math.max(1,Number(req.query.page)||1),limit=Math.min(30,Math.max(1,Number(req.query.limit)||12)); const filter:any={status:'visible'}; const search=clean(req.query.search,120); if(search) filter.$text={$search:search}; if(req.query.category&&COMMUNITY_CATEGORIES.includes(String(req.query.category)))filter.category=req.query.category; if(req.query.tab==='unanswered')filter['answers.0']={$exists:false}; if(req.query.tab==='following'&&req.communityUser) filter['author.userId']=req.communityUser._id; if(req.query.tab==='saved') filter.savedBy={$elemMatch:actor(req)}; if(req.query.tab==='mine'&&req.communityUser)filter['author.userId']=req.communityUser._id; if(req.query.tab==='my_answers'&&req.communityUser)filter['answers.author.userId']=req.communityUser._id; if(req.query.tab==='recent'){const threeDaysAgo=new Date();threeDaysAgo.setDate(threeDaysAgo.getDate()-3);filter.createdAt={$gte:threeDaysAgo};} let rows:any[],total:number; if(req.query.tab==='trending'){const agg=await CommunityQuestion.aggregate([{$match:filter},{$addFields:{trendScore:{$add:[{$multiply:['$views',1]},{$multiply:[{$size:{$ifNull:['$likedBy',[]]}},3]},{$multiply:[{$size:{$ifNull:['$answers',[]]}},5]}]}}},{$sort:{trendScore:-1,createdAt:-1}},{$facet:{data:[{$skip:(page-1)*limit},{$limit:limit}],total:[{$count:'n'}]}}]);rows=agg[0]?.data||[];total=agg[0]?.total[0]?.n||0;}else{const sort:any=req.query.tab==='liked'?{'likedBy':-1,createdAt:-1}:{createdAt:-1};[rows,total]=await Promise.all([CommunityQuestion.find(filter).sort(sort).skip((page-1)*limit).limit(limit),CommunityQuestion.countDocuments(filter)]);} const scores=rows.map((q:any)=>trendScore(q)).sort((a:number,b:number)=>b-a); const threshold=scores[Math.floor(scores.length*0.3)]??0; res.json({success:true,data:rows.map((q:any)=>serialize(q,req,false,trendScore(q)>=threshold&&trendScore(q)>5)),pagination:{page,total,pages:Math.ceil(total/limit)}}); });
router.get('/questions/:slug', async (req:any,res)=>{ const q=await CommunityQuestion.findOne({slug:req.params.slug,status:'visible'}); if(!q)return res.status(404).json({success:false,message:'Question not found'}); const viewer=actorKey(actor(req)); if(!q.viewedBy.includes(viewer)){q.views++;q.viewedBy.push(viewer);if(q.viewedBy.length>5000)q.viewedBy=q.viewedBy.slice(-4000);await q.save();} res.json({success:true,data:serialize(q,req,true)}); });
router.post('/questions',writeLimiter,async(req:any,res)=>{ const title=clean(req.body.title,180),body=clean(req.body.body,20000),category=clean(req.body.category,50),tags=(Array.isArray(req.body.tags)?req.body.tags:[]).map((x:any)=>clean(x,30).toLowerCase()).filter(Boolean).slice(0,5); if(title.length<12||body.length<30||!COMMUNITY_CATEGORIES.includes(category))return res.status(400).json({success:false,message:'Add a specific title, details, and valid category'}); const duplicate=await CommunityQuestion.findOne({title:new RegExp(`^${title.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')}$`,'i'),status:'visible'}); if(duplicate)return res.status(409).json({success:false,message:'A similar question already exists',slug:duplicate.slug}); const secret=crypto.randomBytes(24).toString('hex'),guestName=clean(req.body.guestName,50)||'QuickTools Guest'; const author=req.communityUser?{userId:req.communityUser._id,name:req.communityUser.name,avatar:req.communityUser.avatar,isGuest:false}:{name:guestName,isGuest:true}; let slug=slugify(title); if(await CommunityQuestion.exists({slug}))slug+=`-${Date.now().toString(36)}`; const q=await CommunityQuestion.create({slug,title,body,excerpt:body.slice(0,240),category,tags,author,guestSecretHash:req.communityUser?undefined:hash(secret)}); if (req.communityUser) await awardXP(req.communityUser._id, 5); res.status(201).json({success:true,data:serialize(q,req),guestSecret:req.communityUser?undefined:secret}); });
router.patch('/questions/:slug',writeLimiter,async(req:any,res)=>{ const q=await CommunityQuestion.findOne({slug:req.params.slug}); if(!q)return res.status(404).json({success:false}); if(!owns(q,req,req.body.guestSecret))return res.status(403).json({success:false,message:'Owner access required'}); const title=clean(req.body.title||q.title,180),body=clean(req.body.body||q.body,20000); if(title.length<12||body.length<30)return res.status(400).json({success:false}); q.title=title;q.body=body;q.excerpt=body.slice(0,240);await q.save();res.json({success:true,data:serialize(q,req,true)}); });
router.delete('/questions/:slug',writeLimiter,async(req:any,res)=>{ const q=await CommunityQuestion.findOne({slug:req.params.slug});if(!q)return res.status(404).json({success:false});if(!owns(q,req,req.body.guestSecret))return res.status(403).json({success:false,message:'Owner access required'});await q.deleteOne();res.json({success:true}); });
async function toggleArray(req:any,res:Response,field:'likedBy'|'savedBy'){const q=await CommunityQuestion.findOne({slug:req.params.slug,status:'visible'});if(!q)return res.status(404).json({success:false});const a=actor(req),key=actorKey(a),list:any[]=q[field] as any;const index=list.findIndex(x=>actorKey(x)===key);if(index>=0)list.splice(index,1);else list.push(a);await q.save();res.json({success:true,active:index<0,count:list.length});}
router.post('/questions/:slug/like',writeLimiter,(req,res)=>toggleArray(req,res,'likedBy')); router.post('/questions/:slug/save',writeLimiter,(req,res)=>toggleArray(req,res,'savedBy'));
router.post('/questions/:slug/answers',writeLimiter,async(req:any,res)=>{const q=await CommunityQuestion.findOne({slug:req.params.slug,status:'visible'});if(!q)return res.status(404).json({success:false});const body=clean(req.body.body,12000);if(body.length<10)return res.status(400).json({success:false,message:'Answer is too short'});const secret=crypto.randomBytes(24).toString('hex'),author=req.communityUser?{userId:req.communityUser._id,name:req.communityUser.name,avatar:req.communityUser.avatar,isGuest:false}:{name:clean(req.body.guestName,50)||'QuickTools Guest',isGuest:true};q.answers.push({body,author,guestSecretHash:req.communityUser?undefined:hash(secret)} as any);await q.save();if(q.author.userId&&String(q.author.userId)!==String(req.communityUser?._id))await CommunityNotification.create({userId:q.author.userId,type:'answer',message:`${author.name} answered your question`,questionSlug:q.slug}); if (req.communityUser) await awardXP(req.communityUser._id, 10); res.status(201).json({success:true,data:serialize(q,req,true),guestSecret:req.communityUser?undefined:secret});});
router.post('/questions/:slug/answers/:answerId/like',writeLimiter,async(req:any,res)=>{const q=await CommunityQuestion.findOne({slug:req.params.slug});const answer=q?.answers.id(req.params.answerId);if(!q||!answer)return res.status(404).json({success:false});const a=actor(req),key=actorKey(a),index=answer.likedBy.findIndex((x:any)=>actorKey(x)===key);if(index>=0)answer.likedBy.splice(index,1);else answer.likedBy.push(a);await q.save();res.json({success:true,active:index<0,count:answer.likedBy.length});});
router.post('/questions/:slug/answers/:answerId/accept',writeLimiter,async(req:any,res)=>{const q=await CommunityQuestion.findOne({slug:req.params.slug});if(!q)return res.status(404).json({success:false});if(!owns(q,req,req.body.guestSecret))return res.status(403).json({success:false,message:'Question owner access required'});const answer=q.answers.id(req.params.answerId);if(!answer)return res.status(404).json({success:false});q.answers.forEach((x:any)=>x.isAccepted=false);answer.isAccepted=true;await q.save(); if (answer.author?.userId) await awardXP(answer.author.userId, 50); res.json({success:true});});
router.put('/questions/:slug/answers/:answerId',writeLimiter,async(req:any,res)=>{const q=await CommunityQuestion.findOne({slug:req.params.slug});if(!q)return res.status(404).json({success:false});const answer=q.answers.id(req.params.answerId);if(!answer)return res.status(404).json({success:false});if(!owns(answer,req,req.body.guestSecret))return res.status(403).json({success:false,message:'Answer owner access required'});const body=clean(req.body.body,12000);if(body.length<10)return res.status(400).json({success:false,message:'Answer is too short'});answer.body=body;await q.save();res.json({success:true,data:serialize(q,req,true)});});
router.delete('/questions/:slug/answers/:answerId',writeLimiter,async(req:any,res)=>{const q=await CommunityQuestion.findOne({slug:req.params.slug});if(!q)return res.status(404).json({success:false});const answer=q.answers.id(req.params.answerId);if(!answer)return res.status(404).json({success:false});if(!owns(answer,req,req.body.guestSecret))return res.status(403).json({success:false,message:'Answer owner access required'});answer.deleteOne();await q.save();res.json({success:true,data:serialize(q,req,true)});});
router.post('/questions/:slug/answers/:answerId/replies',writeLimiter,async(req:any,res)=>{const q=await CommunityQuestion.findOne({slug:req.params.slug,status:'visible'});if(!q)return res.status(404).json({success:false});const answer=q.answers.id(req.params.answerId);if(!answer)return res.status(404).json({success:false});const body=clean(req.body.body,12000);if(body.length<2)return res.status(400).json({success:false,message:'Reply is too short'});const author=req.communityUser?{userId:req.communityUser._id,name:req.communityUser.name,avatar:req.communityUser.avatar,isGuest:false}:{name:clean(req.body.guestName,50)||'QuickTools Guest',isGuest:true};answer.replies.push({body,author} as any);await q.save();res.status(201).json({success:true,data:serialize(q,req,true)});});
router.post('/questions/:slug/answers/:answerId/replies/:replyId/like',writeLimiter,async(req:any,res)=>{const q=await CommunityQuestion.findOne({slug:req.params.slug});const answer=q?.answers.id(req.params.answerId);if(!q||!answer)return res.status(404).json({success:false});const reply=answer.replies.id(req.params.replyId);if(!reply)return res.status(404).json({success:false});const a=actor(req),key=actorKey(a),index=reply.likedBy.findIndex((x:any)=>actorKey(x)===key);if(index>=0)reply.likedBy.splice(index,1);else reply.likedBy.push(a);await q.save();res.json({success:true,active:index<0,count:reply.likedBy.length});});
router.post('/questions/:slug/report',writeLimiter,async(req,res)=>{const q=await CommunityQuestion.findOne({slug:req.params.slug});if(!q)return res.status(404).json({success:false});q.reports++;if(q.reports>=5)q.status='pending';await q.save();res.json({success:true,message:'Report sent to moderation'});});
router.get('/notifications',async(req:any,res)=>{if(!req.communityUser)return res.status(401).json({success:false});const rows=await CommunityNotification.find({userId:req.communityUser._id}).sort({createdAt:-1}).limit(30).lean();res.json({success:true,data:rows});});
router.post('/notifications/read',async(req:any,res)=>{if(!req.communityUser)return res.status(401).json({success:false});await CommunityNotification.updateMany({userId:req.communityUser._id,read:false},{$set:{read:true}});res.json({success:true});});
router.get('/leaderboard', async (req: any, res) => {
  const topUsers = await User.find({}).sort({ xp: -1, createdAt: 1 }).limit(50).select('name avatar xp level badges role').lean();
  let currentUser = null;
  if (req.communityUser) {
    const user = await User.findById(req.communityUser._id).select('name avatar xp level badges role').lean();
    if (user) {
      const rank = await User.countDocuments({ xp: { $gt: user.xp } }) + 1;
      currentUser = { ...user, rank };
    }
  }
  res.json({ success: true, data: { leaderboard: topUsers, currentUser } });
});

export default router;
